//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeTrabalho
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        public int id { get; set; }
        public string nome { get; set; }
        public decimal nota { get; set; }
        public string sinopse { get; set; }
        public int ano { get; set; }
        public int qnt_ep { get; set; }
    }
}
